export const suggestions = [
  'small',
  'medium',
  'large',
  'extreme',
  'Carbon',
  'Titanium',
  'Hydrogenium',
  'Kyberkristall',
  'Cobalt',
  'Iridium',
  'Uraninite',
  'Thorium',
  'Astatine',
  'Hyperdiamond',
  'Dilithium',
  'Deuterium',
  'small Carbon',
  'small Titanium',
  'small Hydrogenium',
  'small Kyberkristall',
  'small Cobalt',
  'small Iridium',
  'small Uraninite',
  'small Thorium',
  'small Astatine',
  'small Hyperdiamond',
  'small Dilithium',
  'small Deuterium',
  'medium Carbon',
  'medium Titanium',
  'medium Hydrogenium',
  'medium Kyberkristall',
  'medium Cobalt',
  'medium Iridium',
  'medium Uraninite',
  'medium Thorium',
  'medium Astatine',
  'medium Hyperdiamond',
  'medium Dilithium',
  'medium Deuterium',
  'large Carbon',
  'large Titanium',
  'large Hydrogenium',
  'large Kyberkristall',
  'large Cobalt',
  'large Iridium',
  'large Uraninite',
  'large Thorium',
  'large Astatine',
  'large Hyperdiamond',
  'large Dilithium',
  'large Deuterium',
  'extreme Carbon',
  'extreme Titanium',
  'extreme Hydrogenium',
  'extreme Kyberkristall',
  'extreme Cobalt',
  'extreme Iridium',
  'extreme Uraninite',
  'extreme Thorium',
  'extreme Astatine',
  'extreme Hyperdiamond',
  'extreme Dilithium',
  'extreme Deuterium',
  'Carbon-Titanium',
  'Carbon-Hydrogenium',
  'Carbon-Kyberkristall',
  'Carbon-Cobalt',
  'Carbon-Iridium',
  'Carbon-Uraninite',
  'Carbon-Thorium',
  'Carbon-Astatine',
  'Carbon-Hyperdiamond',
  'Carbon-Dilithium',
  'Carbon-Deuterium',
  'Titanium-Carbon',
  'Titanium-Hydrogenium',
  'Titanium-Kyberkristall',
  'Titanium-Cobalt',
  'Titanium-Iridium',
  'Titanium-Uraninite',
  'Titanium-Thorium',
  'Titanium-Astatine',
  'Titanium-Hyperdiamond',
  'Titanium-Dilithium',
  'Titanium-Deuterium',
  'Hydrogenium-Carbon',
  'Hydrogenium-Titanium',
  'Hydrogenium-Kyberkristall',
  'Hydrogenium-Cobalt',
  'Hydrogenium-Iridium',
  'Hydrogenium-Uraninite',
  'Hydrogenium-Thorium',
  'Hydrogenium-Astatine',
  'Hydrogenium-Hyperdiamond',
  'Hydrogenium-Dilithium',
  'Hydrogenium-Deuterium',
  'Kyberkristall-Carbon',
  'Kyberkristall-Titanium',
  'Kyberkristall-Hydrogenium',
  'Kyberkristall-Cobalt',
  'Kyberkristall-Iridium',
  'Kyberkristall-Uraninite',
  'Kyberkristall-Thorium',
  'Kyberkristall-Astatine',
  'Kyberkristall-Hyperdiamond',
  'Kyberkristall-Dilithium',
  'Kyberkristall-Deuterium',
  'Cobalt-Carbon',
  'Cobalt-Titanium',
  'Cobalt-Hydrogenium',
  'Cobalt-Kyberkristall',
  'Cobalt-Iridium',
  'Cobalt-Uraninite',
  'Cobalt-Thorium',
  'Cobalt-Astatine',
  'Cobalt-Hyperdiamond',
  'Cobalt-Dilithium',
  'Cobalt-Deuterium',
  'Iridium-Carbon',
  'Iridium-Titanium',
  'Iridium-Hydrogenium',
  'Iridium-Kyberkristall',
  'Iridium-Cobalt',
  'Iridium-Uraninite',
  'Iridium-Thorium',
  'Iridium-Astatine',
  'Iridium-Hyperdiamond',
  'Iridium-Dilithium',
  'Iridium-Deuterium',
  'Uraninite-Carbon',
  'Uraninite-Titanium',
  'Uraninite-Hydrogenium',
  'Uraninite-Kyberkristall',
  'Uraninite-Cobalt',
  'Uraninite-Iridium',
  'Uraninite-Thorium',
  'Uraninite-Astatine',
  'Uraninite-Hyperdiamond',
  'Uraninite-Dilithium',
  'Uraninite-Deuterium',
  'Thorium-Carbon',
  'Thorium-Titanium',
  'Thorium-Hydrogenium',
  'Thorium-Kyberkristall',
  'Thorium-Cobalt',
  'Thorium-Iridium',
  'Thorium-Uraninite',
  'Thorium-Astatine',
  'Thorium-Hyperdiamond',
  'Thorium-Dilithium',
  'Thorium-Deuterium',
  'Astatine-Carbon',
  'Astatine-Titanium',
  'Astatine-Hydrogenium',
  'Astatine-Kyberkristall',
  'Astatine-Cobalt',
  'Astatine-Iridium',
  'Astatine-Uraninite',
  'Astatine-Thorium',
  'Astatine-Hyperdiamond',
  'Astatine-Dilithium',
  'Astatine-Deuterium',
  'Hyperdiamond-Carbon',
  'Hyperdiamond-Titanium',
  'Hyperdiamond-Hydrogenium',
  'Hyperdiamond-Kyberkristall',
  'Hyperdiamond-Cobalt',
  'Hyperdiamond-Iridium',
  'Hyperdiamond-Uraninite',
  'Hyperdiamond-Thorium',
  'Hyperdiamond-Astatine',
  'Hyperdiamond-Dilithium',
  'Hyperdiamond-Deuterium',
  'Dilithium-Carbon',
  'Dilithium-Titanium',
  'Dilithium-Hydrogenium',
  'Dilithium-Kyberkristall',
  'Dilithium-Cobalt',
  'Dilithium-Iridium',
  'Dilithium-Uraninite',
  'Dilithium-Thorium',
  'Dilithium-Astatine',
  'Dilithium-Hyperdiamond',
  'Dilithium-Deuterium',
  'Deuterium-Carbon',
  'Deuterium-Titanium',
  'Deuterium-Hydrogenium',
  'Deuterium-Kyberkristall',
  'Deuterium-Cobalt',
  'Deuterium-Iridium',
  'Deuterium-Uraninite',
  'Deuterium-Thorium',
  'Deuterium-Astatine',
  'Deuterium-Hyperdiamond',
  'Deuterium-Dilithium'
];
