<?php

return [
    'spacecrafts' => [
        // Fighters
        [
            'name' => 'Merlin',
            'details_id' => 1,
            'attack' => 70,
            'defense' => 30,
            'combat' => 100,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 0,
            'speed' => 200,
            'operation_speed' => 0,
            'crew_limit' => 1,
            'build_time' => 30,
            'research_cost' => 1,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 35],
                ['resource_name' => 'Titanium', 'amount' => 30],
                ['resource_name' => 'Hydrogenium', 'amount' => 10],
            ],
        ],
        [
            'name' => 'Comet',
            'details_id' => 2,
            'attack' => 110,
            'defense' => 90,
            'combat' => 200,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 5,
            'speed' => 150,
            'operation_speed' => 0,
            'crew_limit' => 1,
            'build_time' => 60,
            'research_cost' => 2,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 80],
                ['resource_name' => 'Hydrogenium', 'amount' => 40],
                ['resource_name' => 'Kyberkristall', 'amount' => 30],
            ],
        ],
        [
            'name' => 'Javelin',
            'details_id' => 3,
            'attack' => 250,
            'defense' => 120,
            'combat' => 370,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 10,
            'speed' => 150,
            'operation_speed' => 0,
            'crew_limit' => 2,
            'build_time' => 180,
            'research_cost' => 4,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 250],
                ['resource_name' => 'Titanium', 'amount' => 150],
                ['resource_name' => 'Hydrogenium', 'amount' => 90],
                ['resource_name' => 'Kyberkristall', 'amount' => 60],
            ],
        ],
        [
            'name' => 'Sentinel',
            'details_id' => 4,
            'attack' => 200,
            'defense' => 250,
            'combat' => 450,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 15,
            'speed' => 125,
            'operation_speed' => 0,
            'crew_limit' => 2,
            'build_time' => 240,
            'research_cost' => 6,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 250],
                ['resource_name' => 'Titanium', 'amount' => 180],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 60],
                ['resource_name' => 'Cobalt', 'amount' => 40],
            ],
        ],
        [
            'name' => 'Probe',
            'details_id' => 5,
            'attack' => 300,
            'defense' => 420,
            'combat' => 720,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 20,
            'speed' => 120,
            'operation_speed' => 0,
            'crew_limit' => 4,
            'build_time' => 600,
            'research_cost' => 9,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 350],
                ['resource_name' => 'Titanium', 'amount' => 300],
                ['resource_name' => 'Hydrogenium', 'amount' => 150],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
                ['resource_name' => 'Cobalt', 'amount' => 75],
                ['resource_name' => 'Iridium', 'amount' => 50],
            ],
        ],
        [
            'name' => 'Ares',
            'details_id' => 6,
            'attack' => 800,
            'defense' => 500,
            'combat' => 1300,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 30,
            'speed' => 100,
            'operation_speed' => 0,
            'crew_limit' => 6,
            'build_time' => 1200,
            'research_cost' => 12,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 600],
                ['resource_name' => 'Titanium', 'amount' => 450],
                ['resource_name' => 'Hydrogenium', 'amount' => 250],
                ['resource_name' => 'Kyberkristall', 'amount' => 200],
                ['resource_name' => 'Cobalt', 'amount' => 120],
                ['resource_name' => 'Iridium', 'amount' => 60],
                ['resource_name' => 'Uraninite', 'amount' => 40],
            ],
        ],
        [
            'name' => 'Nova',
            'details_id' => 7,
            'attack' => 600,
            'defense' => 900,
            'combat' => 1500,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 50,
            'speed' => 80,
            'operation_speed' => 0,
            'crew_limit' => 8,
            'build_time' => 3600,
            'research_cost' => 15,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 900],
                ['resource_name' => 'Titanium', 'amount' => 700],
                ['resource_name' => 'Hydrogenium', 'amount' => 400],
                ['resource_name' => 'Kyberkristall', 'amount' => 350],
                ['resource_name' => 'Cobalt', 'amount' => 200],
                ['resource_name' => 'Iridium', 'amount' => 120],
                ['resource_name' => 'Uraninite', 'amount' => 80],
                ['resource_name' => 'Thorium', 'amount' => 40],
                ['resource_name' => 'Astatine', 'amount' => 20],
            ],
        ],
        [
            'name' => 'Horus',
            'details_id' => 8,
            'attack' => 1300,
            'defense' => 1700,
            'combat' => 3000,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 250,
            'speed' => 60,
            'operation_speed' => 0,
            'crew_limit' => 15,
            'build_time' => 7200,
            'research_cost' => 21,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 1800],
                ['resource_name' => 'Titanium', 'amount' => 1500],
                ['resource_name' => 'Hydrogenium', 'amount' => 800],
                ['resource_name' => 'Kyberkristall', 'amount' => 600],
                ['resource_name' => 'Cobalt', 'amount' => 400],
                ['resource_name' => 'Iridium', 'amount' => 250],
                ['resource_name' => 'Uraninite', 'amount' => 200],
                ['resource_name' => 'Thorium', 'amount' => 120],
                ['resource_name' => 'Astatine', 'amount' => 60],
                ['resource_name' => 'Hyperdiamond', 'amount' => 50],
                ['resource_name' => 'Dilithium', 'amount' => 40],
            ],
        ],
        [
            'name' => 'Reaper',
            'details_id' => 9,
            'attack' => 3750,
            'defense' => 5500,
            'combat' => 9250,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 1000,
            'speed' => 50,
            'operation_speed' => 0,
            'crew_limit' => 60,
            'build_time' => 28800,
            'research_cost' => 30,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 5000],
                ['resource_name' => 'Titanium', 'amount' => 4000],
                ['resource_name' => 'Hydrogenium', 'amount' => 2000],
                ['resource_name' => 'Kyberkristall', 'amount' => 1500],
                ['resource_name' => 'Cobalt', 'amount' => 1200],
                ['resource_name' => 'Iridium', 'amount' => 1000],
                ['resource_name' => 'Uraninite', 'amount' => 600],
                ['resource_name' => 'Thorium', 'amount' => 400],
                ['resource_name' => 'Astatine', 'amount' => 200],
                ['resource_name' => 'Hyperdiamond', 'amount' => 100],
                ['resource_name' => 'Dilithium', 'amount' => 100],
                ['resource_name' => 'Deuterium', 'amount' => 100],
            ],
        ],
        // Miners
        [
            'name' => 'Mole',
            'details_id' => 10,
            'attack' => 15,
            'defense' => 35,
            'combat' => 50,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 100,
            'speed' => 50,
            'operation_speed' => 60,
            'crew_limit' => 1,
            'build_time' => 60,
            'research_cost' => 1,
            'unlocked' => true,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 80],
                ['resource_name' => 'Hydrogenium', 'amount' => 40],
                ['resource_name' => 'Kyberkristall', 'amount' => 20],
            ],
        ],
        [
            'name' => 'Titan',
            'details_id' => 11,
            'attack' => 30,
            'defense' => 50,
            'combat' => 80,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 250,
            'speed' => 75,
            'operation_speed' => 300,
            'crew_limit' => 5,
            'build_time' => 300,
            'research_cost' => 5,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 400],
                ['resource_name' => 'Titanium', 'amount' => 350],
                ['resource_name' => 'Hydrogenium', 'amount' => 200],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
                ['resource_name' => 'Cobalt', 'amount' => 50],
                ['resource_name' => 'Iridium', 'amount' => 40],
            ],
        ],
        // Cargo
        [
            'name' => 'Nomad',
            'details_id' => 12,
            'attack' => 10,
            'defense' => 10,
            'combat' => 20,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 500,
            'speed' => 50,
            'operation_speed' => 90,
            'crew_limit' => 2,
            'build_time' => 60,
            'research_cost' => 2,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 140],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 80],
                ['resource_name' => 'Kyberkristall', 'amount' => 40],
            ],
        ],
        [
            'name' => 'Hercules',
            'details_id' => 13,
            'attack' => 20,
            'defense' => 40,
            'combat' => 60,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 5000,
            'speed' => 80,
            'operation_speed' => 480,
            'crew_limit' => 8,
            'build_time' => 480,
            'research_cost' => 6,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 500],
                ['resource_name' => 'Titanium', 'amount' => 400],
                ['resource_name' => 'Hydrogenium', 'amount' => 300],
                ['resource_name' => 'Kyberkristall', 'amount' => 150],
                ['resource_name' => 'Cobalt', 'amount' => 80],
                ['resource_name' => 'Iridium', 'amount' => 40],
            ],
        ],
        // Salvage
        /* [
            'name' => 'Collector',
            'details_id' => 14,
            'attack' => 20,
            'defense' => 40,
            'combat' => 60,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 250,
            'speed' => 60,
            'operation_speed' => 120,
            'crew_limit' => 1,
            'build_time' => 120,
            'research_cost' => 3,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 200],
                ['resource_name' => 'Titanium', 'amount' => 160],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 80],
                ['resource_name' => 'Cobalt', 'amount' => 40],
            ],
        ],
        [
            'name' => 'Reclaimer',
            'details_id' => 15,
            'attack' => 35,
            'defense' => 55,
            'combat' => 90,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 2000,
            'speed' => 100,
            'operation_speed' => 720,
            'crew_limit' => 4,
            'build_time' => 720,
            'research_cost' => 5,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 700],
                ['resource_name' => 'Titanium', 'amount' => 600],
                ['resource_name' => 'Hydrogenium', 'amount' => 400],
                ['resource_name' => 'Kyberkristall', 'amount' => 250],
                ['resource_name' => 'Cobalt', 'amount' => 150],
                ['resource_name' => 'Iridium', 'amount' => 80],
                ['resource_name' => 'Uraninite', 'amount' => 40],
            ],
        ], */
    ],
];
