<?php

return [
    'spacecrafts' => [
        [
            'name' => 'Merlin',
            'details_id' => 1,
            'combat' => 120,
            'count' => 0,
            'cargo' => 10,
            'speed' => 200,
            'crewLimit' => 1,
            'buildTime' => 10,
            'researchCost' => 1,
            'unlocked' => true,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 300],
                ['resource_name' => 'Titanium', 'amount' => 300],
                ['resource_name' => 'Hydrogenium', 'amount' => 200],
            ],
        ],
        [
            'name' => 'Comet',
            'details_id' => 2,
            'combat' => 180,
            'count' => 0,
            'cargo' => 15,
            'speed' => 300,
            'crewLimit' => 1,
            'buildTime' => 15,
            'researchCost' => 1,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 400],
                ['resource_name' => 'Titanium', 'amount' => 400],
                ['resource_name' => 'Hydrogenium', 'amount' => 300],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Javelin',
            'details_id' => 3,
            'combat' => 320,
            'count' => 0,
            'cargo' => 20,
            'speed' => 250,
            'crewLimit' => 2,
            'buildTime' => 30,
            'researchCost' => 2,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 500],
                ['resource_name' => 'Titanium', 'amount' => 500],
                ['resource_name' => 'Hydrogenium', 'amount' => 400],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
                ['resource_name' => 'Cobalt', 'amount' => 200],
            ],
        ],
        [
            'name' => 'Sentinel',
            'details_id' => 4,
            'combat' => 550,
            'count' => 0,
            'cargo' => 30,
            'speed' => 180,
            'crewLimit' => 3,
            'buildTime' => 60,
            'researchCost' => 3,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 700],
                ['resource_name' => 'Titanium', 'amount' => 700],
                ['resource_name' => 'Hydrogenium', 'amount' => 500],
                ['resource_name' => 'Kyberkristall', 'amount' => 200],
                ['resource_name' => 'Cobalt', 'amount' => 250],
                ['resource_name' => 'Iridium', 'amount' => 300],
            ],
        ],
        [
            'name' => 'Probe',
            'details_id' => 5,
            'combat' => 900,
            'count' => 0,
            'cargo' => 80,
            'speed' => 180,
            'crewLimit' => 5,
            'buildTime' => 90,
            'researchCost' => 5,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 700],
                ['resource_name' => 'Titanium', 'amount' => 800],
                ['resource_name' => 'Hydrogenium', 'amount' => 500],
                ['resource_name' => 'Kyberkristall', 'amount' => 400],
                ['resource_name' => 'Cobalt', 'amount' => 300],
                ['resource_name' => 'Iridium', 'amount' => 300],
                ['resource_name' => 'Uraninite', 'amount' => 300],
            ],
        ],
        [
            'name' => 'Ares',
            'details_id' => 6,
            'combat' => 1500,
            'count' => 0,
            'cargo' => 500,
            'speed' => 150,
            'crewLimit' => 8,
            'buildTime' => 120,
            'researchCost' => 8,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 1000],
                ['resource_name' => 'Titanium', 'amount' => 1200],
                ['resource_name' => 'Hydrogenium', 'amount' => 800],
                ['resource_name' => 'Kyberkristall', 'amount' => 500],
                ['resource_name' => 'Cobalt', 'amount' => 350],
                ['resource_name' => 'Iridium', 'amount' => 300],
                ['resource_name' => 'Uraninite', 'amount' => 250],
                ['resource_name' => 'Thorium', 'amount' => 400],
            ],
        ],
        [
            'name' => 'Nova',
            'details_id' => 7,
            'combat' => 2500,
            'count' => 0,
            'cargo' => 2500,
            'speed' => 120,
            'crewLimit' => 12,
            'buildTime' => 180,
            'researchCost' => 12,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 1200],
                ['resource_name' => 'Titanium', 'amount' => 1500],
                ['resource_name' => 'Hydrogenium', 'amount' => 1100],
                ['resource_name' => 'Kyberkristall', 'amount' => 600],
                ['resource_name' => 'Cobalt', 'amount' => 500],
                ['resource_name' => 'Iridium', 'amount' => 450],
                ['resource_name' => 'Uraninite', 'amount' => 400],
                ['resource_name' => 'Thorium', 'amount' => 350],
                ['resource_name' => 'Astatine', 'amount' => 350]
            ],
        ],
        [
            'name' => 'Horus',
            'details_id' => 8,
            'combat' => 5500,
            'count' => 0,
            'cargo' => 6000,
            'speed' => 100,
            'crewLimit' => 20,
            'buildTime' => 300,
            'researchCost' => 20,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 2000],
                ['resource_name' => 'Titanium', 'amount' => 2000],
                ['resource_name' => 'Hydrogenium', 'amount' => 1500],
                ['resource_name' => 'Kyberkristall', 'amount' => 900],
                ['resource_name' => 'Cobalt', 'amount' => 800],
                ['resource_name' => 'Iridium', 'amount' => 700],
                ['resource_name' => 'Uraninite', 'amount' => 600],
                ['resource_name' => 'Thorium', 'amount' => 500],
                ['resource_name' => 'Astatine', 'amount' => 400],
                ['resource_name' => 'Hyperdiamond', 'amount' => 300],
            ],
        ],
        [
            'name' => 'Reaper',
            'details_id' => 9,
            'combat' => 25000,
            'count' => 0,
            'cargo' => 15000,
            'speed' => 80,
            'crewLimit' => 60,
            'buildTime' => 600,
            'researchCost' => 35,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 3000],
                ['resource_name' => 'Titanium', 'amount' => 3000],
                ['resource_name' => 'Hydrogenium', 'amount' => 2000],
                ['resource_name' => 'Kyberkristall', 'amount' => 1200],
                ['resource_name' => 'Cobalt', 'amount' => 950],
                ['resource_name' => 'Iridium', 'amount' => 900],
                ['resource_name' => 'Uraninite', 'amount' => 800],
                ['resource_name' => 'Thorium', 'amount' => 500],
                ['resource_name' => 'Astatine', 'amount' => 300],
                ['resource_name' => 'Hyperdiamond', 'amount' => 300],
                ['resource_name' => 'Dilithium', 'amount' => 250],
                ['resource_name' => 'Deuterium', 'amount' => 200],
            ],
        ],
        [
            'name' => 'Mole',
            'details_id' => 10,
            'combat' => 80,
            'count' => 0,
            'cargo' => 500,
            'speed' => 100,
            'crewLimit' => 1,
            'buildTime' => 10,
            'researchCost' => 1,
            'unlocked' => true,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 300],
                ['resource_name' => 'Titanium', 'amount' => 400],
                ['resource_name' => 'Hydrogenium', 'amount' => 200],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Titan',
            'details_id' => 11,
            'combat' => 220,
            'count' => 0,
            'cargo' => 3500,
            'speed' => 150,
            'crewLimit' => 5,
            'buildTime' => 100,
            'researchCost' => 10,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 600],
                ['resource_name' => 'Titanium', 'amount' => 700],
                ['resource_name' => 'Hydrogenium', 'amount' => 800],
                ['resource_name' => 'Kyberkristall', 'amount' => 500],
                ['resource_name' => 'Cobalt', 'amount' => 250],
                ['resource_name' => 'Iridium', 'amount' => 150],
            ],
        ],
        [
            'name' => 'Nomad',
            'details_id' => 12,
            'combat' => 50,
            'count' => 0,
            'cargo' => 1000,
            'speed' => 100,
            'crewLimit' => 2,
            'buildTime' => 15,
            'researchCost' => 1,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 300],
                ['resource_name' => 'Titanium', 'amount' => 300],
                ['resource_name' => 'Hydrogenium', 'amount' => 200],
            ],
        ],
        [
            'name' => 'Hercules',
            'details_id' => 13,
            'combat' => 180,
            'count' => 0,
            'cargo' => 8000,
            'speed' => 80,
            'crewLimit' => 8,
            'buildTime' => 180,
            'researchCost' => 8,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 750],
                ['resource_name' => 'Titanium', 'amount' => 900],
                ['resource_name' => 'Hydrogenium', 'amount' => 600],
                ['resource_name' => 'Kyberkristall', 'amount' => 400],
                ['resource_name' => 'Cobalt', 'amount' => 200],
            ],
        ],
        /* [
            'name' => 'Collector',
            'details_id' => 14,
            'combat' => 100,
            'count' => 0,
            'cargo' => 500,
            'speed' => 120,
            'crewLimit' => 2,
            'buildTime' => 25,
            'researchCost' => 3,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 300],
                ['resource_name' => 'Titanium', 'amount' => 400],
                ['resource_name' => 'Hydrogenium', 'amount' => 150],
                ['resource_name' => 'Kyberkristall', 'amount' => 50],
                ['resource_name' => 'Cobalt', 'amount' => 50],
            ],
        ], */
        /* [
            'name' => 'Reclaimer',
            'details_id' => 15,
            'combat' => 250,
            'count' => 0,
            'cargo' => 2500,
            'speed' => 100,
            'crewLimit' => 6,
            'buildTime' => 180,
            'researchCost' => 12,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 700],
                ['resource_name' => 'Titanium', 'amount' => 800],
                ['resource_name' => 'Hydrogenium', 'amount' => 900],
                ['resource_name' => 'Kyberkristall', 'amount' => 500],
                ['resource_name' => 'Cobalt', 'amount' => 300],
                ['resource_name' => 'Iridium', 'amount' => 200],
                ['resource_name' => 'Uraninite', 'amount' => 100],
            ],
        ], */
    ],
];
