<?php

return [
    'spacecrafts' => [
        [
            'name' => 'Merlin',
            'details_id' => 1,
            'combat' => 100,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 10,
            'speed' => 150,
            'operation_speed' => 0,
            'crew_limit' => 1,
            'build_time' => 50,
            'research_cost' => 1,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 250],
                ['resource_name' => 'Titanium', 'amount' => 250],
                ['resource_name' => 'Hydrogenium', 'amount' => 250],
            ],
        ],
        [
            'name' => 'Comet',
            'details_id' => 2,
            'combat' => 180,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 15,
            'speed' => 125,
            'operation_speed' => 0,
            'crew_limit' => 1,
            'build_time' => 90,
            'research_cost' => 2,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 400],
                ['resource_name' => 'Titanium', 'amount' => 400],
                ['resource_name' => 'Hydrogenium', 'amount' => 300],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Javelin',
            'details_id' => 3,
            'combat' => 320,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 20,
            'speed' => 110,
            'operation_speed' => 0,
            'crew_limit' => 2,
            'build_time' => 180,
            'research_cost' => 4,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 500],
                ['resource_name' => 'Titanium', 'amount' => 500],
                ['resource_name' => 'Hydrogenium', 'amount' => 400],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
                ['resource_name' => 'Cobalt', 'amount' => 200],
            ],
        ],
        [
            'name' => 'Sentinel',
            'details_id' => 4,
            'combat' => 550,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 30,
            'speed' => 100,
            'operation_speed' => 0,
            'crew_limit' => 3,
            'build_time' => 300,
            'research_cost' => 6,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 700],
                ['resource_name' => 'Titanium', 'amount' => 700],
                ['resource_name' => 'Hydrogenium', 'amount' => 500],
                ['resource_name' => 'Kyberkristall', 'amount' => 200],
                ['resource_name' => 'Cobalt', 'amount' => 250],
                ['resource_name' => 'Iridium', 'amount' => 200],
            ],
        ],
        [
            'name' => 'Probe',
            'details_id' => 5,
            'combat' => 900,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 80,
            'speed' => 90,
            'operation_speed' => 0,
            'crew_limit' => 5,
            'build_time' => 420,
            'research_cost' => 9,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 700],
                ['resource_name' => 'Titanium', 'amount' => 800],
                ['resource_name' => 'Hydrogenium', 'amount' => 550],
                ['resource_name' => 'Kyberkristall', 'amount' => 350],
                ['resource_name' => 'Cobalt', 'amount' => 350],
                ['resource_name' => 'Iridium', 'amount' => 300],
                ['resource_name' => 'Uraninite', 'amount' => 250],
            ],
        ],
        [
            'name' => 'Ares',
            'details_id' => 6,
            'combat' => 1500,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 500,
            'speed' => 80,
            'operation_speed' => 0,
            'crew_limit' => 8,
            'build_time' => 720,
            'research_cost' => 12,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 1000],
                ['resource_name' => 'Titanium', 'amount' => 1200],
                ['resource_name' => 'Hydrogenium', 'amount' => 800],
                ['resource_name' => 'Kyberkristall', 'amount' => 450],
                ['resource_name' => 'Cobalt', 'amount' => 300],
                ['resource_name' => 'Iridium', 'amount' => 250],
                ['resource_name' => 'Uraninite', 'amount' => 200],
                ['resource_name' => 'Thorium', 'amount' => 300],
            ],
        ],
        [
            'name' => 'Nova',
            'details_id' => 7,
            'combat' => 2500,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 2500,
            'speed' => 70,
            'operation_speed' => 0,
            'crew_limit' => 12,
            'build_time' => 1200,
            'research_cost' => 15,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 1200],
                ['resource_name' => 'Titanium', 'amount' => 1500],
                ['resource_name' => 'Hydrogenium', 'amount' => 1100],
                ['resource_name' => 'Kyberkristall', 'amount' => 600],
                ['resource_name' => 'Cobalt', 'amount' => 450],
                ['resource_name' => 'Iridium', 'amount' => 350],
                ['resource_name' => 'Uraninite', 'amount' => 350],
                ['resource_name' => 'Thorium', 'amount' => 300],
                ['resource_name' => 'Astatine', 'amount' => 250]
            ],
        ],
        [
            'name' => 'Horus',
            'details_id' => 8,
            'combat' => 5500,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 6000,
            'speed' => 60,
            'operation_speed' => 0,
            'crew_limit' => 20,
            'build_time' => 2400,
            'research_cost' => 21,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 2000],
                ['resource_name' => 'Titanium', 'amount' => 2200],
                ['resource_name' => 'Hydrogenium', 'amount' => 1500],
                ['resource_name' => 'Kyberkristall', 'amount' => 1000],
                ['resource_name' => 'Cobalt', 'amount' => 800],
                ['resource_name' => 'Iridium', 'amount' => 700],
                ['resource_name' => 'Uraninite', 'amount' => 600],
                ['resource_name' => 'Thorium', 'amount' => 450],
                ['resource_name' => 'Astatine', 'amount' => 400],
                ['resource_name' => 'Hyperdiamond', 'amount' => 250],
            ],
        ],
        [
            'name' => 'Reaper',
            'details_id' => 9,
            'combat' => 25000,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 15000,
            'speed' => 50,
            'operation_speed' => 0,
            'crew_limit' => 60,
            'build_time' => 3600,
            'research_cost' => 30,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 4000],
                ['resource_name' => 'Titanium', 'amount' => 4000],
                ['resource_name' => 'Hydrogenium', 'amount' => 3000],
                ['resource_name' => 'Kyberkristall', 'amount' => 1500],
                ['resource_name' => 'Cobalt', 'amount' => 1200],
                ['resource_name' => 'Iridium', 'amount' => 1000],
                ['resource_name' => 'Uraninite', 'amount' => 1000],
                ['resource_name' => 'Thorium', 'amount' => 800],
                ['resource_name' => 'Astatine', 'amount' => 750],
                ['resource_name' => 'Hyperdiamond', 'amount' => 600],
                ['resource_name' => 'Dilithium', 'amount' => 500],
                ['resource_name' => 'Deuterium', 'amount' => 500],
            ],
        ],
        [
            'name' => 'Mole',
            'details_id' => 10,
            'combat' => 80,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 500,
            'speed' => 50,
            'operation_speed' => 400,
            'crew_limit' => 1,
            'build_time' => 60,
            'research_cost' => 1,
            'unlocked' => true,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 300],
                ['resource_name' => 'Titanium', 'amount' => 400],
                ['resource_name' => 'Hydrogenium', 'amount' => 200],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Titan',
            'details_id' => 11,
            'combat' => 220,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 3500,
            'speed' => 75,
            'operation_speed' => 3500,
            'crew_limit' => 5,
            'build_time' => 600,
            'research_cost' => 9,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 650],
                ['resource_name' => 'Titanium', 'amount' => 750],
                ['resource_name' => 'Hydrogenium', 'amount' => 850],
                ['resource_name' => 'Kyberkristall', 'amount' => 550],
                ['resource_name' => 'Cobalt', 'amount' => 250],
                ['resource_name' => 'Iridium', 'amount' => 150],
            ],
        ],
        [
            'name' => 'Nomad',
            'details_id' => 12,
            'combat' => 50,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 1000,
            'speed' => 60,
            'operation_speed' => 0,
            'crew_limit' => 2,
            'build_time' => 60,
            'research_cost' => 1,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 350],
                ['resource_name' => 'Titanium', 'amount' => 350],
                ['resource_name' => 'Hydrogenium', 'amount' => 200],
            ],
        ],
        [
            'name' => 'Hercules',
            'details_id' => 13,
            'combat' => 180,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 8000,
            'speed' => 80,
            'operation_speed' => 0,
            'crew_limit' => 8,
            'build_time' => 480,
            'research_cost' => 6,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 800],
                ['resource_name' => 'Titanium', 'amount' => 1000],
                ['resource_name' => 'Hydrogenium', 'amount' => 650],
                ['resource_name' => 'Kyberkristall', 'amount' => 450],
                ['resource_name' => 'Cobalt', 'amount' => 200],
            ],
        ],
        /* [
            'name' => 'Collector',
            'details_id' => 14,
            'combat' => 100,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 500,
            'speed' => 50,
            'operation_speed' => 200,
            'crew_limit' => 2,
            'build_time' => 90,
            'research_cost' => 3,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 300],
                ['resource_name' => 'Titanium', 'amount' => 400],
                ['resource_name' => 'Hydrogenium', 'amount' => 150],
                ['resource_name' => 'Kyberkristall', 'amount' => 50],
                ['resource_name' => 'Cobalt', 'amount' => 50],
            ],
        ], */
        /* [
            'name' => 'Reclaimer',
            'details_id' => 15,
            'combat' => 250,
            'count' => 0,
            'locked_count' => 0,
            'cargo' => 2500,
            'speed' => 70,
            'operation_speed' => 350,
            'crew_limit' => 6,
            'build_time' => 720,
            'research_cost' => 12,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 700],
                ['resource_name' => 'Titanium', 'amount' => 800],
                ['resource_name' => 'Hydrogenium', 'amount' => 900],
                ['resource_name' => 'Kyberkristall', 'amount' => 500],
                ['resource_name' => 'Cobalt', 'amount' => 300],
                ['resource_name' => 'Iridium', 'amount' => 200],
                ['resource_name' => 'Uraninite', 'amount' => 100],
            ],
        ], */
    ],
];
