<?php

return [
    'spacecrafts' => [
        [
            'name' => 'Merlin',
            'details_id' => 1,
            'combat' => 50,
            'count' => 0,
            'cargo' => 20,
            'unitLimit' => 1,
            'buildTime' => 900,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Comet',
            'details_id' => 2,
            'combat' => 150,
            'count' => 0,
            'cargo' => 40,
            'unitLimit' => 1,
            'buildTime' => 720,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Javelin',
            'details_id' => 3,
            'combat' => 400,
            'count' => 0,
            'cargo' => 80,
            'unitLimit' => 1,
            'buildTime' => 1800,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Sentinel',
            'details_id' => 4,
            'combat' => 1000,
            'count' => 0,
            'cargo' => 200,
            'unitLimit' => 1,
            'buildTime' => 900,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Probe',
            'details_id' => 5,
            'combat' => 2500,
            'count' => 0,
            'cargo' => 900,
            'unitLimit' => 1,
            'buildTime' => 600,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Ares',
            'details_id' => 6,
            'combat' => 7000,
            'count' => 0,
            'cargo' => 2700,
            'unitLimit' => 1,
            'buildTime' => 500,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Nova',
            'details_id' => 7,
            'combat' => 20000,
            'count' => 0,
            'cargo' => 6400,
            'unitLimit' => 1,
            'buildTime' => 300,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Horus',
            'details_id' => 8,
            'combat' => 60000,
            'count' => 0,
            'cargo' => 9800,
            'unitLimit' => 1,
            'buildTime' => 1500,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Reaper',
            'details_id' => 9,
            'combat' => 200000,
            'count' => 0,
            'cargo' => 15000,
            'unitLimit' => 1,
            'buildTime' => 1200,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Mole',
            'details_id' => 10,
            'combat' => 10,
            'count' => 0,
            'cargo' => 200,
            'unitLimit' => 1,
            'buildTime' => 1200,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Titan',
            'details_id' => 11,
            'combat' => 100,
            'count' => 0,
            'cargo' => 3200,
            'unitLimit' => 1,
            'buildTime' => 1200,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Nomad',
            'details_id' => 12,
            'combat' => 25,
            'count' => 0,
            'cargo' => 500,
            'unitLimit' => 1,
            'buildTime' => 1200,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Hercules',
            'details_id' => 13,
            'combat' => 250,
            'count' => 0,
            'cargo' => 5000,
            'unitLimit' => 1,
            'buildTime' => 1200,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Collector',
            'details_id' => 14,
            'combat' => 100,
            'count' => 0,
            'cargo' => 450,
            'unitLimit' => 1,
            'buildTime' => 1200,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
        [
            'name' => 'Reclaimer',
            'details_id' => 15,
            'combat' => 450,
            'count' => 0,
            'cargo' => 3600,
            'unitLimit' => 1,
            'buildTime' => 1200,
            'unlocked' => false,
            'costs' => [
                ['resource_name' => 'Carbon', 'amount' => 100],
                ['resource_name' => 'Titanium', 'amount' => 100],
                ['resource_name' => 'Hydrogenium', 'amount' => 100],
                ['resource_name' => 'Kyberkristall', 'amount' => 100],
            ],
        ],
    ],
];
